import { I } from "../icons.js";
import { SAMPLES } from "../samples.js";

const React = window.React;
const { useState } = React;
const h = React.createElement;

export function HeatmapScreen({ model }) {
  const [k, setK] = useState("pos1");
  const [op, setOp] = useState(0.65);
  const [show, setShow] = useState(true);
  const s = SAMPLES[k];
  const positive = k.startsWith("pos");

  return h("div", { className: "content" },
    h("div", { className: "page-header" },
      h("div", null,
        h("h1", { className: "page-title" }, "Visualización Grad-CAM"),
        h("div", { className: "page-sub" }, "HU-002 · Mapa de activación de " + model.name),
      ),
      h("div", { className: "row", style: { gap: 8 } },
        h("select", { className: "select", value: k, onChange: (e) => setK(e.target.value) },
          h("option", { value: "pos1" }, "CASE-0917 · Positivo"),
          h("option", { value: "pos2" }, "CASE-1042 · Positivo"),
          h("option", { value: "neg1" }, "CASE-0863 · Negativo"),
          h("option", { value: "neg2" }, "CASE-0728 · Negativo"),
        ),
        h("button", { className: "btn btn-primary" }, h(I.dl, { size: 14 }), "Descargar PNG"),
      ),
    ),
    h("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 } },
      h("div", { className: "card" },
        h("div", { className: "card-head" },
          h("div", null,
            h("h3", { className: "card-title" }, "Imagen original"),
            h("div", { className: "card-sub" }, "Captura endoscópica · luz blanca"),
          ),
          h("span", { className: "badge badge-neutral" }, "ORIGINAL"),
        ),
        h("div", { style: { padding: 16 } },
          h("div", { className: "heatmap-stage" }, h("img", { src: s.src })),
        ),
      ),
      h("div", { className: "card" },
        h("div", { className: "card-head" },
          h("div", null,
            h("h3", { className: "card-title" }, "Grad-CAM"),
            h("div", { className: "card-sub" }, "Capa layer4.bn3 · " + model.name),
          ),
          h("span", { className: "badge " + (positive ? "badge-pos" : "badge-neg") },
            positive ? "POSITIVO" : "NEGATIVO"),
        ),
        h("div", { style: { padding: 16 } },
          h("div", { className: "heatmap-stage" },
            h("img", { src: s.src }),
            show && h("img", { className: "heat", src: s.heat, style: { opacity: op } }),
          ),
          h("div", { style: { marginTop: 14 } },
            h("div", { className: "row between", style: { marginBottom: 6 } },
              h("span", { className: "section-title", style: { marginBottom: 0 } }, "Opacidad del overlay"),
              h("span", { className: "mono", style: { fontSize: 12 } }, Math.round(op * 100) + "%"),
            ),
            h("input", {
              className: "slider", type: "range",
              min: "0", max: "1", step: "0.01",
              value: op, onChange: (e) => setOp(Number(e.target.value)),
            }),
            h("div", { className: "row", style: { marginTop: 10, gap: 10 } },
              h("label", { className: "row", style: { gap: 6, fontSize: 12 } },
                h("input", { type: "checkbox", checked: show, onChange: (e) => setShow(e.target.checked) }),
                "Mostrar superposición",
              ),
            ),
          ),
        ),
      ),
    ),
    h("div", { style: { display: "grid", gridTemplateColumns: "1fr 1.4fr", gap: 20, marginTop: 20 } },
      h("div", { className: "card card-pad" },
        h("div", { className: "section-title" }, "Leyenda de activación"),
        h("div", { className: "legend" },
          h("span", { className: "legend-label" }, "Baja"),
          h("div", { className: "legend-bar" }),
          h("span", { className: "legend-label" }, "Alta"),
        ),
      ),
      h("div", { className: "card card-pad" },
        h("div", { className: "section-title" }, "Explicación clínica"),
        positive
          ? h("p", { style: { fontSize: 13.5, color: "var(--ink-700)", lineHeight: 1.6, margin: 0 } },
              "El modelo concentra su atención en el ",
              h("strong", null, "cuadrante superior-derecho"),
              " (x: 360–440, y: 180–260), donde se observa una zona de mucosa con ",
              h("strong", null, "patrón nodular irregular y enrojecimiento focal"),
              " compatible con cambios inflamatorios crónicos asociados a colonización por H. pylori.")
          : h("p", { style: { fontSize: 13.5, color: "var(--ink-700)", lineHeight: 1.6, margin: 0 } },
              "La activación es ",
              h("strong", null, "difusa y de baja magnitud"),
              ", sin focos claros sobre la mucosa. El modelo no encuentra patrones discriminativos."),
        h("div", { className: "alert alert-info", style: { marginTop: 14 } },
          h(I.info, { size: 16 }),
          h("div", null,
            h("strong", null, "Interpretación asistida. "),
            "El Grad-CAM muestra qué mira el modelo, no por qué. Validar con criterio clínico.",
          ),
        ),
      ),
    ),
  );
}
